<?php
/**
 * Created by PhpStorm.
 * User: CX
 * Date: 2018/3/15
 * Time: 10:38
 */

namespace frontend\modules\Api\modules\V1\modules\GetHeart;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'frontend\modules\Api\modules\V1\modules\GetHeart\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->modules = [
            'activity' => ['class' => 'frontend\modules\Api\modules\V1\modules\GetHeart\modules\Activity\Module',],
        ];
    }
}